/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package audiojoinerbot;

import org.slf4j.LoggerFactory;
import org.telegram.telegrambots.meta.TelegramBotsApi;
import org.telegram.telegrambots.meta.exceptions.TelegramApiException;
import org.telegram.telegrambots.updatesreceivers.DefaultBotSession;


public class Main  {
    private final static org.slf4j.Logger logger = LoggerFactory.getLogger(Main.class);
    public static void main(String[] args) {
        try {
            logger.info("Application Started");
            TelegramBotsApi botsApi = new TelegramBotsApi(DefaultBotSession.class);
            botsApi.registerBot(new AudioBot());
        } catch (TelegramApiException ex) {
            logger.error(ex.getMessage());
        }
        catch(Exception ex){
            logger.error(ex.getMessage());
        }
    }   
}
